# Generated by Django 5.0 on 2024-05-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_userprofile_options"),
        ("dogs", "0003_dog_adoption_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="liked_dogs",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by_users", to="dogs.dog"
            ),
        ),
    ]
