# Generated by Django 5.0 on 2024-05-15 09:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("breed", models.CharField(max_length=80)),
                ("age", models.IntegerField()),
                (
                    "featured_image",
                    cloudinary.models.CloudinaryField(
                        default="placeholder", max_length=255, verbose_name="image"
                    ),
                ),
                ("description", models.TextField()),
                ("gender", models.CharField(max_length=10)),
                ("good_with_children", models.BooleanField(default=True)),
            ],
        ),
    ]
