# Generated by Django 5.0 on 2024-05-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dog",
            options={
                "ordering": ["name"],
                "verbose_name": "Dog",
                "verbose_name_plural": "Dogs",
            },
        ),
    ]
