# Generated by Django 5.0 on 2024-05-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0002_alter_dog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="adoption_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("pending", "Pending"),
                    ("adopted", "Adopted"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
