# Generated by Django 5.0 on 2024-05-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0003_dog_adoption_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="good_with_other_dogs",
            field=models.BooleanField(default=True),
        ),
    ]
